name: forecasting_method_recommendation2
dependencies:
  - python>=3.7,<4.0
  - altair>=4.1.0,<5.0.0
  - pandas>=1.3.4,<2.0.0
  - numpy>=1.21.2,<2.0.0
  - scipy>=1.7.1
  - scikit-learn>=1.0
  - statsmodels>=0.13.0,<0.14.0
  - pip
  - pip:
    - streamlit>=1.2.0,<2.0.0
    - matplotlib>=3.5.0
    - torch>=1.10.0,<2.0.0
    - pmdarima>=1.8.4,<2.0.0
